// SPDX-License-Identifier: MIT

/**
 * Smartefact Gradle conventions - Java
 *
 * @author Laurent Pireyn
 */

plugins {
    id("org.smartefact.base")
    id("java")
}

tasks.withType<JavaCompile> {
    with (options) {
        // Normalize Java sources encoding
        encoding = Charsets.UTF_8.name()
        // Fork to ensure fork options are applied
        isFork = true
        forkOptions {
            // Normalize line separator in files generated by annotation processors
            jvmArgumentProviders.add { listOf("-Dline.separator=\\n") }
        }
        javaModuleVersion = provider { project.version.toString() }
        debugOptions.debugLevel = "source,lines,vars"
        // Enable various warnings
        isWarnings = true
        isDeprecation = true
        compilerArgumentProviders.add { listOf(
            // Enable all recommended warnings
            "-Xlint",
            // Disable some warnings
            "-Xlint:-missing-explicit-ctor",
        ) }
    }
}

testing {
    jvmTestSuites {
        targets.configureEach {
            testTask {
                // Enable assert keyword in tests
                jvmArgs("-ea")
                // Use a build subdirectory as temporary directory
                systemProperty(
                    "java.io.tmpdir",
                    layout.buildDirectory.dir("tmp/$name").get().asFile.path
                )
            }
        }
    }
}

// JAR Manifest
// Reference: https://docs.oracle.com/en/java/javase/21/docs/specs/jar/jar.html
tasks.jar {
    manifest {
        attributes(mutableMapOf<String, String>().apply {
            put("Implementation-Title", project.name)
            put("Implementation-Version", project.version.toString())
            put("Implementation-Vendor", "Smartefact")
        })
    }
}

tasks.withType<Javadoc> {
    standardOptions {
        version()
        author()
        linkSource()
    }
}
